[package]
name = "day-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.4"
itertools = "0.13.0"
regex = "1.10.2"

[[bench]]
name = "example"
harness = false
